services:

  backend:
    image: ghcr.io/miracleplus/litellm-expand/backend:latest
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    build:
      context: ./backend
    volumes:
      - ./evalscope:/app/evalscope
    environment:
      - TZ=Asia/Shanghai
  frontend:
    image: ghcr.io/miracleplus/litellm-expand/frontend:latest
    restart: always
    ports:
      - 4000:80
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    environment:
      - TZ=Asia/Shanghai