services:

  backend:
    image: backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    build:
      context: ./backend
  frontend:
    image: frontend
    restart: always
    ports:
      - 4000:80
    build:
      context: ./frontend
      args:
        - NODE_ENV=production